solutiondrive_product_bundle:
  resource:  |
    alias: solutiondrive.product_bundle
    section: admin
    permission: true
    templates: SyliusAdminBundle:Crud
    except: ['show']
    redirect: index
    grid: solutiondrive_admin_product_bundle
    vars:
      all:
        subheader: solutiondrive.ui.manage_product_bundles
        templates:
          form: "@SolutionDriveSyliusProductBundlesPlugin/Admin/ProductBundle/_form.html.twig"
      index:
        icon: sitemap
  type: sylius.resource
