sylius_grid:
    grids:
        solutiondrive_admin_product_bundle:
            driver:
                name: doctrine/orm
                options:
                    class: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundle
            fields:
                product.name:
                    type: string
                    label: sylius.ui.name
                product.code:
                    type: string
                    label: sylius.ui.code
                slots:
                    type: twig
                    label: solutiondrive.ui.slots
                    options:
                        template: "@SolutionDriveSyliusProductBundlesPlugin/Admin/ProductBundle/Grid/Field/slots.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                subitem:
                    product:
                        type: links
                        label: solutiondrive.ui.manage_product_bundle_product
                        options:
                            icon: cube
                            links:
                                update:
                                    label: sylius.ui.edit_product
                                    icon: list
                                    route: sylius_admin_product_update
                                    parameters:
                                        id: resource.getProductId


        sylius_admin_product:
            actions:
                subitem:
                    bundle:
                        type: links
                        label: solutiondrive.ui.edit_product_bundle
                        options:
                            icon: sitemap
                            visible: resource.getProductBundle
                            links:
                                index:
                                    label: solutiondrive.ui.show_bundle
                                    icon: list
                                    route: solutiondrive_admin_product_bundle_update
                                    parameters:
                                        id: resource.getProductBundleId
