sylius_grid:
  grids:
    solutiondrive_admin_product_bundle:
      driver:
        name: doctrine/orm
        options:
          class: SolutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundle
      fields:
        name:
          type: string
          label: sylius.ui.name
        code:
          type: string
          label: sylius.ui.code
      actions:
        main:
          create:
            type: create
        item:
          update:
            type: update
          delete:
            type: delete
