sylius_resource:
    resources:
        solutiondrive.product_bundle:
            classes:
                model: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundle
                interface: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleInterface
                form: solutionDrive\SyliusProductBundlesPlugin\Form\Type\ProductBundleType
                repository: solutionDrive\SyliusProductBundlesPlugin\Repository\ProductBundleRepository
        solutiondrive.product_bundle_slot:
            classes:
                model: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleSlot
                interface: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleSlotInterface
                form: solutionDrive\SyliusProductBundlesPlugin\Form\Type\ProductBundleSlotType


sylius_product:
    resources:
        product:
            classes:
                model: solutionDrive\SyliusProductBundlesPlugin\Entity\Product
