sylius_resource:
    resources:
        solutiondrive.product_bundle:
            classes:
                model: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundle
                form: solutionDrive\SyliusProductBundlesPlugin\Form\Type\ProductBundleType

sylius_product:
    resources:
        product:
            classes:
                model: solutionDrive\SyliusProductBundlesPlugin\Entity\Product
