services:
    # Menu-Entry
    solutiondrive.product_bundles.menu_listener.main:
        class: solutionDrive\SyliusProductBundlesPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addProductBundlesMenu }

    # ProductBundle - Services
    solutiondrive.product_bundles.product_bundle_registry:
        class: solutionDrive\SyliusProductBundlesPlugin\Service\ProductBundleRegistry
        arguments:
            - "@solutiondrive.repository.product_bundle"

    solutiondrive.product_bundles.product_bundle_creator:
        class: solutionDrive\SyliusProductBundlesPlugin\Service\ProductBundleCreator
        arguments:
            - "@solutiondrive.factory.product_bundle"
            - "@solutiondrive.product_bundles.product_bundle_manipulator"


    solutiondrive.product_bundles.slot_finder:
        class: solutionDrive\SyliusProductBundlesPlugin\Service\SlotFinder

    solutiondrive.product_bundles.product_bundle_manipulator:
        class: solutionDrive\SyliusProductBundlesPlugin\Service\ProductBundleManipulator
        arguments:
            - "@solutiondrive.factory.product_bundle_slot"


    solutiondrive.product_bundles.fixture.example_factory.product_bundle:
        class: solutionDrive\SyliusProductBundlesPlugin\Fixture\Factory\ProductBundleExampleFactory
        arguments:
            - "@solutiondrive.product_bundles.product_bundle_creator"
            - "@sylius.repository.product"

    solutiondrive.product_bundles.fixture.product_bundle:
        class: solutionDrive\SyliusProductBundlesPlugin\Fixture\ProductBundleFixture
        arguments:
            - "@solutiondrive.manager.product_bundle"
            - "@solutiondrive.product_bundles.fixture.example_factory.product_bundle"
        tags:
            - {name: sylius_fixtures.fixture}

    solutiondrive.product_bundles.block_event_listener.product_bundle.update.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@SolutionDriveSyliusProductBundlesPlugin/Admin/ProductBundle/_javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.solutiondrive.admin.product_bundle.update.javascripts, method: onBlockEvent }

    solutiondrive.product_bundles.block_event_listener.product_bundle.create.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@SolutionDriveSyliusProductBundlesPlugin/Admin/ProductBundle/_javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.solutiondrive.admin.product_bundle.create.javascripts, method: onBlockEvent }
