solutiondrive_product_bundle:
  resource:  |
    alias: solutiondrive.product_bundle
    templates: SyliusAdminBundle:Crud
    section: admin
    grid: solutiondrive_admin_product_bundle
  type: sylius.resource
