solutiondrive_product_bundle:
  resource:  |
    alias: solutiondrive.product_bundle
    section: admin
    permission: true
    templates: SyliusAdminBundle:Crud
    section: admin
    except: ['show']
    redirect: index
    grid: solutiondrive_admin_product_bundle
  type: sylius.resource

solutiondrive_admin_prduct_bundle_create:
    path: /product-bundles/new
    methods: [GET, POST]
    defaults:
        _controller: solutiondrive.controller.product_bundle:createAction
        _sylius:
            section: admin
            permission: true
            template: SyliusAdminBundle:Crud:create.html.twig
            redirect: solutiondrive_admin_product_bundle_update
            vars:
                subheader: sylius.ui.manage_product_bundles
