solutiondrive_product_bundle:
  resource:  |
    alias: solutiondrive.product_bundle
    section: admin
    permission: true
    templates: SyliusAdminBundle:Crud
    section: admin
    except: ['show']
    redirect: index
    grid: solutiondrive_admin_product_bundle
  type: sylius.resource
