SolutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundle:
    type: entity
    table: solutiondrive_product_bundle
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255
        code:
            type: string
            length: 255
            unique: true

    oneToOne:
        product:
            targetEntity: Sylius\Component\Core\Model\Product
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                unique: true

    oneToMany:
        slots:
            targetEntity: SolutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleSlot
            mappedBy: bundle
