solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundle:
    type: mappedSuperclass
    table: solutiondrive_product_bundle
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToOne:
        product:
            targetEntity: Sylius\Component\Product\Model\ProductInterface
            inversedBy: productBundle
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                unique: true

        presentationSlot:
            targetEntity: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleSlotInterface
            joinColumn:
                name: presentation_slot_id
                referencedColumnName: id
                onDelete: 'SET NULL'

    oneToMany:
        slots:
            targetEntity: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleSlotInterface
            mappedBy: bundle
            cascade: ["persist"]
            orphanRemoval: true
            orderBy:
                position: ASC
