SolutionDrive\SyliusProductBundlesPlugin\Entity\Product:
    type: entity
    table: sylius_product

    oneToOne:
        productBundle:
            targetEntity: SolutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundle
            mappedBy: product
