solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleSlot:
    type: entity
    table: solutiondrive_product_bundle_slot
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    uniqueConstraints:
        slotNameUnique:
            columns:
                - bundle_id
                - name

    fields:
        name:
            type: string
            length: 255
        position:
            type: smallint
            default: 0

    manyToOne:
        bundle:
            targetEntity: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleInterface
            inversedBy: slots
            joinColumn:
                name: bundle_id
                referencedColumnName: id
                nullable: false
                onDelete: 'CASCADE'

    manyToMany:
        products:
            targetEntity: Sylius\Component\Product\Model\ProductInterface
            joinTable:
                name: solutiondrive_product_bundle_slot_product
                joinColumns:
                    product_bundle_slot_id:
                        referencedColumnName: id
                        onDelete: 'CASCADE'
                inverseJoinColumns:
                    product_id:
                        referencedColumnName: id
