solutionDrive\SyliusProductBundlesPlugin\Entity\Product:
    type: mappedSuperclass
    table: sylius_product

    oneToOne:
        productBundle:
            targetEntity: solutionDrive\SyliusProductBundlesPlugin\Entity\ProductBundleInterface
            mappedBy: product
